### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by srikanthtummala** [srikanthtummala/vay#2]
# Task 2

## Objective

Please create an example of a CircleCI /Jenkins CI job or bash scripts that will automatically:
- [ ] Take the latest released by the team application image from docker register
- [ ] Evaluate linked to this image test and coverage reports
- [ ] Connect via ssh to a system HIL.
- [ ] Deploy this new image and execute linked system integration tests.
- [ ] Collect application Performance metrics (CPU and RAM usage).
- [ ] Generate a report from this data and send it to the target group.
- [ ] Generate CircleCI/Jenkins CI approval flow to Approve release test results and image for deployment to production. 

## Interfaces Details

_**Following are the services/servers endpoints which will be part of build process for above requirement.**_ 

[Git Repository](https://github.com/srikanthtummala/vay)
[Docker Registry](https://srikanthtummala.jfrog.io/artifactory/st-lab-docker/)
[Artifacts Registry](https://srikanthtummala.jfrog.io/ui/repos/tree/General/st-lab-docker)
[Influxdb](https://us-east-1-1.aws.cloud2.influxdata.com/orgs/26504bfd304f6621)
[Grafana Dashboards](https://grafana.com/orgs/srikanthsoa/dashboards)
[Jenkins Server](http://localhost:8080)
[Vault Server](https://portal.cloud.hashicorp.com/orgs/67d2f701-1fbc-4538-9efc-650bd161e831/projects/9b4ef44e-1c35-49ce-9f9e-e716f8ad35b2)
